#!/bin/bash
set -e

function random_string {
    head /dev/urandom | LC_ALL=C tr -dc a-z0-9 | head -c 12
}

PASSWORD=$(random_string)
CONTAINER_NAME="vg-redis-$(random_string)"

NETWORK=""
if [ -n "$VG_DOCKER_NETWORK" ]; then
    NETWORK="--network=$VG_DOCKER_NETWORK"
fi

CONTAINER=$(docker run \
    --detach \
    --publish 6379 \
    --label vantage.redis=1 \
    $NETWORK \
    --name "$CONTAINER_NAME" \
    redis redis-server --requirepass "$PASSWORD")

if [ -n "$VG_DOCKER_NETWORK" ]; then
    HOST="$CONTAINER_NAME"
else
    HOST=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' $CONTAINER)
fi

DB="redis://h:$PASSWORD@$HOST:6379"

vg __env REDIS_URL "$DB"

echo "$DB"
