#!/bin/bash
set -e

function help {
    cat << EOF >&2
usage: vantage redis new|rm|shell|web

This plugin assumes that a redis URI will be available at the ENV variable
REDIS_URL. It should look something like this:

    redis://h:PASSWORD@HOST:PORT

vg redis new
    Create a new redis instance and save the URI to the default env file (if it
    exists)

vg redis rm [-a]
    Remove the redis container, or all containers if the -a flag is set

vg redis shell
    Open a shell pointed at the redis container

vg redis web
    Start up a redis-commander instance pointed at redis. Open up HOST:8081 to
    view
EOF
}

if [ -n "$VG_SHOW_HELP" ]; then
    help
    exit
fi

echo "vantage: redis: No command given"
help
exit 1
