#!/bin/bash
set -e

function stop_and_remove {
    docker ps --quiet --all --filter "label=vantage.redis" | while IFS='' read -r CID
    do
        if [ -n "$VG_DOCKER_NETWORK" ]; then
            HOST=$(docker inspect -f '{{ .Name }}' $CID | cut -c2-)
        else
            HOST=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' $CID)
        fi
        if [ "$1" == "$HOST" ]; then
            echo "Removing $CID"
            docker stop "$CID" > /dev/null
            docker rm "$CID" > /dev/null
            break
        fi
    done
}

function stop_and_remove_all {
    docker ps --quiet --all --filter "label=vantage.redis" | while IFS='' read -r CID
    do
        echo "Removing $CID"
        docker stop "$CID" > /dev/null
        docker rm "$CID" > /dev/null
    done
}

while getopts ":a" opt; do
    case $opt in
        a)
            stop_and_remove_all
            exit
            ;;
    esac
done

URL=$(vg __env REDIS_URL)
HOST=${URL##*@}
HOST=${HOST%%:*}

stop_and_remove "$HOST"
