#!/bin/bash
set -e

function stop_and_remove {
    docker ps --quiet --all --filter "label=vantage.redis" | while IFS='' read -r CID
    do
        if [ -n "$1" ]; then
            IP=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' $CID)
            if [ "$1" != "$IP" ]; then
                break
            fi
        fi
        echo "Removing $CID"
        docker stop "$CID" > /dev/null
        docker rm "$CID" > /dev/null
    done
}

while getopts ":a" opt; do
    case $opt in
        a)
            stop_and_remove
            exit
            ;;
    esac
done

URL=$(vg __env REDIS_URL)
IP=${URL##*@}
IP=${IP%%:*}

stop_and_remove "$IP"
