#!/bin/bash
set -e

REDIS_URL=$(vg __env REDIS_URL)

PROTO=$(echo $REDIS_URL | grep '://' | sed -e's,^\(.*://\).*,\1,g')
URL=$(echo $REDIS_URL | sed -e s,$PROTO,,g)

USER_PASSWORD=$(echo $URL | grep @ | cut -d@ -f1)
PASSWORD=$(echo $USER_PASSWORD | grep : | cut -d: -f2)

HOST_PORT=`echo $URL | sed -e s,$USER_PASSWORD@,,g | cut -d/ -f1`
PORT=`echo $HOST_PORT | grep : | cut -d: -f2`
if [ -n "$PORT" ]; then
    HOST=`echo $HOST_PORT | grep : | cut -d: -f1`
else
    HOST=$HOST_PORT
fi

NETWORK=""
if [ -n "$VG_DOCKER_NETWORK" ]; then
    NETWORK="--network=$VG_DOCKER_NETWORK"
fi

docker run \
    --interactive \
    --tty \
    --rm \
    "$NETWORK" \
    redis redis-cli -h "$HOST" -p "$PORT" -a "$PASSWORD"
