#!/bin/bash
set -e

REDIS_URL=$(vg __env REDIS_URL)

IMAGE=$(docker images -q vantage/redis-browser:latest)
if [ -z "$IMAGE" ]; then
    DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
    docker build --tag vantage/redis-browser:latest "$DIR"
fi

NETWORK=""
if [ -n "$VG_DOCKER_NETWORK" ]; then
    NETWORK="--network=$VG_DOCKER_NETWORK"
fi

docker run \
    --publish 4567 \
    --rm \
    "$NETWORK" \
    vantage/redis-browser \
        --bind 0.0.0.0 \
        --port 4567 \
        --url "$REDIS_URL"
